version: "3.7"

services:
 database:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=isptube
      - POSTGRES_PASSWORD=isptube
      - POSTGRES_DB=isptube
 redis:
    image: redis:7.2.4 
    ports:
      - 6379:6379    
 app:
    build: .
    container_name: isptube
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
